### ISSUE TITLE
Calling clearRoutes() multiple times causes error

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/PokeMap-1#36]
Please make sure that your `clearRoutes()` method can be called multiple times without causing errors. The error I get is the following
`Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

Looking at your `clearRoutes()` function

``` (javascript)
function clearRoutes(){
    if(route && route.removeFrom) {
        route.removeFrom(mymap);
    }
}
```

my guess is that the error is caused when `route.removeFrom(mymap)` is called the second time. Maybe this small change already fixes the issue:

``` (javascript)
function clearRoutes(){
    if(route && route.removeFrom) {
        route.removeFrom(mymap);
        route = null; // <---- line added
    }
}
```

**Comment by gqinami** [comment]
@johartl , the latest pull request https://github.com/PokemonGoers/PokeMap-1/pull/41/commits/cc90e90895b6671eb67b3f93855c3ed2504d4e8a
should close this issue as well (also npm package updated). Did them in the same PR as for the other issue, since it was a really small fix.   If so, can we close this?

**Comment by johartl** [comment]
I agree.
