### ISSUE TITLE
Pokemon location over time

### ISSUE THREAD

**Issue by gqinami** [PokemonGoers/PokeMap-1#8]
@sacdallago we at PokeMap-1 would like to ask about how are we going to approach the task of presenting the location of pokemons in the map over time. Will we have 2 or three options, like: 
- Past;
- Present;
- Prediction?

Or should we implement a slider that will change the location of pokemons while it is moved depending on the time when the pokemon appeared in a certain location?

And also, if we will have only 2 options, should we send separate requests to the backend for the data, and we would not need to get the appearedOn attribute, or should we have a single request to get all the data we need, together with the appearedOn, and depending on what do we need to present, we can filter it by the appearedOn attribute (in frontend)?

We suggest the first approach (backend), because the second one would be too heavy for the frontend. 

Thanks a lot,
D7 :)

**Comment by gyachdav** [comment]
you will have past, present and future 😆 .  The slider can be of course time limited into the past - let's say a week. The future time frame can be between 30 minutes to 1 day. 

As to your second question I recommend having a test for payload size before querying for the actual data. In cases where the appearances (past,present and future) are sparse it makes sense not to over burden the back end with a series of queries and get all data in one go. In the inverse case you will have no choice but sending multiple queries as the user changes the time range (using the slider).

**Comment by sacdallago** [comment]
Thanks @gyachdav 
Yes, as Guy said @gqinami you will have past, present and future. Though let me break it down for you even more:
1. Past: this data comes from @PokemonGoers/pokedata . They will have to supply you with a function (an API call) to get the tweets in a certain time-range. Since in 5 years we will have 5 years of data ( :joy: ) you might want to, as Guy said, only display up to a maximum of 1 week time-frame, but you should still be able to go 1, 2, 5 years in the past. Guys of project A have to make sure that you can only retrieve data for one week (aka: asing for a bigger time-range will answer with a `400` HTML code) and you will have to reflect this limitation graphically with the GUI somehow. This might be an example: https://sg.finance.yahoo.com/echarts?s=EURSGD%3DX#symbol=EURSGD=X;range=1d Notice that in your case the slider should not reach the `max` span.
   1 week here is a figurative value, it makes sense to see how much data actually get's written in a week, but worst case scenario we have caching, I'm trying to set up redundant and distributed servers,... so requests should be answered fairly quickly.
2. Present: This data comes from the @PokemonGoers/hashpokemongo team. They are implementing a live-twitter streamer. It is different from the stuff that project A does because it is limited to a certain area, it is direct (whereas project A's miner is a bit slower in getting the live-tweets) and it **won't** save to the database, but only be stored in the current user's session! You should work in collaboration with this team to come up with the best way to implement this. I suggested they use websockets to do this, but that implies setting up a server, thus it might make sense that you also collaborate with project A. Suggestion: go one step at the time!
3. Future: The predictions are provided by @PokemonGoers/predictpokemon-2 I lack the technical know-how to tell you exactly how they are gonna magically predict for a given location and a given time-span what the probability for each pokemon to appear is, but at the end of the day this will also be part of project A in the sense that project A should expose an API call where you specify location an upperbound (+30min, +3600min) and then they will return you a JSON objects with strength of the prediction, location, time and type of pokemon ( @goldbergtatyana right?)

**Comment by goldbergtatyana** [comment]
Yes, @sacdallago, this is how point #3 will look like. The machine learning group of https://github.com/orgs/PokemonGoers/teams/predictpokemon-2 will predict:  
1. All pokemons that will appear within the next 30mins (maybe more, is a feature to be determined) within a radius of 10km from a users location
2. One particular Pokemon that will appear within the next 30 mins (maybe more, as above) worldwide, while the world is partitioned in squares of 100km (maybe more, is also tba)

**Comment by gqinami** [comment]
Since all the discussion for the interface is at PokemonGoers/Catch-em-all#24, and it is decided what we will show in the map, closing this issue.
